server:
  port: 9001
  servlet:
    context-path: /api/v1/index-service

solrUrl: http://${SVC_SOLR}/solr/p2p-marketplace_shard1_replica_n1/
solrUsername: ${solrUsername}
solrPassword: ${solrPassword}

springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: index-service
  data:
    mongodb:
      uri: mongodb://root:${mongodb-root-password}@${MONGODB_SERVICE_HOST}:${MONGODB_SERVICE_PORT}
      database: p2p

secret: mvpp2p
errorMsgMap:
  ERR_DETAIL_NOT_FOUND: "Details could not be found. {0}"
  ERR_SAVING_DATA: "Error in saving data. {0}"
  ERR_UPDATING_DATA: "Error in updating data. {0}"
  ERR_DELETING_DATA: "Error in deleting data. {0}"
  ERR_JSON_TRANFORMATION_FAILURE: "Tranformation Fails. {0}"
  ERR_RESPONSE_NOT_FOUND: "No Response Received. {0}"
  ERR_RESPONSE_BODY_NOT_FOUND: "Details not found. {0}"
  ERR_AUTHENTICATION: "Unauthorized Access : {0}"